src/CompanyManagementBundle/Form/RegistrationType.php
<?php

namespace CompanyManagementBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('email', 'email')
//            ->add('password', 'repeated', array(
//                'first_options'  => array('label' => 'Password'),
//                'second_options' => array('label' => 'Repeat Password'),
//                'type' => 'password'
//            ))
            ->add('dateAdded', 'datetime')
            ->add('address')
            ->add('zipCode')
            ->add('city')
            ->add('telephone')
            ->add('hourlyRate')
            ->add('company')
            ->add('department')
            ->add('managedDepartment')
            ->add('role');
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }

    // For Symfony 2.x
    public function getName()
    {
        return $this->getBlockPrefix();
    }
}

src/CompanyManagementBundle/Controller/HomeController.php
<?php

namespace CompanyManagementBundle\Controller;

use CompanyManagementBundle\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class HomeController extends Controller {

    public function homeAction() {

        $user = $this->getUser();

        if(!$user instanceof User){
            return $this->redirectToRoute('fos_user_security_login');
        }

        return $this->render('CompanyManagementBundle:Home:home.html.twig', array(
            'user' => $user
        ));
    }

}

src/CompanyManagementBundle/Resources/views/Home/home.html.twig
{% extends "::base.html.twig" %}

{% block body %}
    <div class="entry">
        <div class="tablewrapper">
            <div class="table">

                <div class="row">
                    <div class="cell2">
                        Personal data:
                    </div>
                    <div class="cell1">
                    </div>
                    <div class="cell center">

                    </div>
                </div>

                <div class="row">
                    <div class="cell">
                        Name:
                    </div>
                    <div class="cell">
                        {{ user.firstName }}
                    </div>
                    <div class="cell center">
                        {% image '@CompanyManagementBundle/Resources/images/avatar.gif' %}
                        <img src="{{ asset_url }}" alt="Bledzik"/>
                        {% endimage %}
                    </div>
                </div>

                <div class="row">
                    <div class="cell">
                        Surname:
                    </div>
                    <div class="cell">
                        {{ user.lastName }}
                    </div>
                    <div class="cell">
                    </div>
                </div>

                <div class="row">
                    <div class="cell">
                        {% if user.department is not null %}

                            Department:

                        {% endif %}
                    </div>
                    <div class="cell">

                        {% if user.department is not null %}

                            {{ user.department.name }}

                        {% endif %}
                    </div>
                    <div class="cell">
                    </div>
                </div>

                <div class="row">
                    <div class="cell">
                        {% if user.parent is not null %}

                        Boss:

                        {% endif %}
                    </div>
                    <div class="cell">
                        {% if user.parent is not null %}

                        {{ user.parent.firstName }} {{ user.parent.lastName }}

                        {% endif %}
                    </div>
                    <div class="cell center">
                        <input type="submit" value="Start work">
                    </div>
                </div>

                <div class="row">
                    <div class="cell">
                        Number of hours worked:
                    </div>
                    <div class="cell">
                        $Ilosc
                    </div>
                    <div class="cell center">
                        <input type="submit" value="End work">
                    </div>
                </div>

            </div>
        </div>
</div>
    <div class="container">
    </div>

{% endblock %}